### ISSUE TITLE
How to filter null values

### ISSUE THREAD

**Issue by pocin** [keboola/php-filter#1]
Maybe I am doing something wrong, but in my child job generic extractor config setting
```
... 
  "recursionFilter": "recipients.mailingList!=null",
```
doesn't filter out this

```
{
"recipients": {
    "mailingList": null
    }
}
```

Is there a gotcha?

**Comment by odinuv** [comment]
Hi,
yes there is `recipients.mailingList!=null` compares to string `'null'`. You can compare against an empty value with `recipients.mailingList!=`

**Comment by odinuv** [comment]
Fixed in https://github.com/keboola/developers-docs/commit/6fcce00dbc900359614a3946becdb19c64e24091 and in https://github.com/keboola/php-filter/commit/a021d2ef4e5c9915f996ec85efd5f8d15319a2f1
